language: python
python:
    - "2.7"
sudo: required
dist: trusty
before_install:
    - sudo apt-get install -y mercurial libfreetype6-dev
    - sudo apt-get build-dep -y python-pygame
    - pip install hg+http://bitbucket.org/pygame/pygame
    - python -c "import pygame"
install: "pip install -r requirements.txt"
script: "nosetests tests"
after_success: "COVERALLS_REPO_TOKEN=$coveralls_token coveralls"
after_failure: "COVERALS_REPO_TOKEN=$coveralls_token coveralls"
