#!/bin/bash

XVFB=`which Xvfb`
if [ "$?" -eq 1 ];
then
    echo "Xvfb not found."
    exit 1
fi

$XVFB :99 -ac &
PID_XVFB="$!"
export DISPLAY=:99

coverage run --source=components -m pytest
result=$?

kill $PID_XVFB
exit $result
